### ISSUE TITLE
您好，请问thinkrag这块有没有跟xinference结合的呢？

### ISSUE THREAD

**Issue by shnulailai** [wzdavid/ThinkRAG#1]
作者您好，请问thinkrag这块有没有跟xinference结合的呢？ollama在服务器上装了几天确实装不上去了。

**Comment by wzdavid** [comment]
项目用的LLamaIndex框架，原本就支持xinference。建议您参照文档，在server/models下增加相关代码即可
https://docs.llamaindex.ai/en/stable/examples/llm/xinference_local_deployment/

**Comment by shnulailai** [comment]
> 您参照文档，在server/models下增加相关

好的好的，感谢David老师
