### ISSUE TITLE
请问对知识库有没有删除的操作

### ISSUE THREAD

**Issue by shnulailai** [wzdavid/ThinkRAG#2]
您好，我部署下来有几个问题：
（1）知识库管理中，有没有删除的功能呢？找不到相关的按钮
（2）在设置模块中，显示高级设置后对prompt进行设置之后怎么保存生效呢？

**Comment by wzdavid** [comment]
谢谢您提出的问题，这两点目前还没有实现，将在后续代码中实现

**Comment by wzdavid** [comment]
知识库管理已可以删除文档，并增加了分页功能

**Comment by shnulailai** [comment]
> 知识库管理已可以删除文档，并增加了分页功能

好的，谢谢wzdavid，我尝试一下

**Comment by shnulailai** [comment]
> 知识库管理已可以删除文档，并增加了分页功能

大卫老师，没有看到相关的删除入口，按钮之类的
![Uploading image.png…]()

**Comment by shnulailai** [comment]
> 知识库管理已可以删除文档，并增加了分页功能

大卫老师，界面上，没有看到相应的点击删除按钮之类的？
![问题反馈](https://github.com/user-attachments/assets/f2ac9aa8-851a-4f0f-8abf-90dce14db88e)

**Comment by shnulailai** [comment]
> > 知识库管理已可以删除文档，并增加了分页功能
> 
> 好的，谢谢wzdavid，我尝试一下

没有问题了，谢谢wzdavid老师
