### ISSUE TITLE
pip问题

### ISSUE THREAD

**Issue by shenxiaolong57** [wzdavid/ThinkRAG#5]
运行pip install -r requirements.txt出现以下问题
  Using cached pydeck-0.9.0-py2.py3-none-any.whl.metadata (4.1 kB)
  Using cached pydeck-0.9.0b1-py2.py3-none-any.whl.metadata (4.1 kB)
INFO: pip is still looking at multiple versions of thinc to determine which version is compatible with other requirements. This could take a while.
  Using cached pydeck-0.9.0b0-py2.py3-none-any.whl.metadata (4.1 kB)
  Using cached pydeck-0.8.1b1-py2.py3-none-any.whl.metadata (3.9 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached pydeck-0.8.1b0-py2.py3-none-any.whl.metadata (3.9 kB)
  Using cached pydeck-0.8.0-py2.py3-none-any.whl.metadata (3.9 kB)
  Using cached pydeck-0.8.0b4-py2.py3-none-any.whl.metadata (3.9 kB)
Collecting pyarrow>=7.0 (from streamlit->-r requirements.txt (line 27))
  Using cached pyarrow-16.1.0-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-16.0.0-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-15.0.2-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-15.0.1-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-15.0.0-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-14.0.2-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-14.0.1-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-14.0.0-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-13.0.0-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-12.0.1-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
  Using cached pyarrow-12.0.0-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
Collecting pandas<3,>=1.4.0 (from streamlit->-r requirements.txt (line 27))
  Using cached pandas-2.2.2-cp310-cp310-win_amd64.whl.metadata (19 kB)
  Using cached pandas-2.2.1-cp310-cp310-win_amd64.whl.metadata (19 kB)
  Using cached pandas-2.2.0-cp310-cp310-win_amd64.whl.metadata (19 kB)
  Using cached pandas-2.1.4-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached pandas-2.1.3-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached pandas-2.1.2-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached pandas-2.1.0-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached pandas-2.0.3-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached pandas-2.0.2-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached pandas-2.0.1-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached pandas-2.0.0-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached pandas-1.5.3-cp310-cp310-win_amd64.whl.metadata (12 kB)
  Using cached pandas-1.5.2-cp310-cp310-win_amd64.whl.metadata (12 kB)
  Using cached pandas-1.5.1-cp310-cp310-win_amd64.whl.metadata (11 kB)
  Using cached pandas-1.5.0-cp310-cp310-win_amd64.whl.metadata (11 kB)
  Using cached pandas-1.4.4-cp310-cp310-win_amd64.whl.metadata (12 kB)
  Using cached pandas-1.4.3-cp310-cp310-win_amd64.whl.metadata (12 kB)
  Using cached pandas-1.4.2-cp310-cp310-win_amd64.whl.metadata (12 kB)
  Using cached pandas-1.4.1-cp310-cp310-win_amd64.whl.metadata (12 kB)
  Using cached pandas-1.4.0-cp310-cp310-win_amd64.whl.metadata (12 kB)
Collecting onnxruntime>=1.14.1 (from chromadb->-r requirements.txt (line 2))
  Using cached onnxruntime-1.19.0-cp310-cp310-win_amd64.whl.metadata (4.5 kB)
  Using cached onnxruntime-1.18.1-cp310-cp310-win_amd64.whl.metadata (4.5 kB)
  Using cached onnxruntime-1.18.0-cp310-cp310-win_amd64.whl.metadata (4.4 kB)
  Using cached onnxruntime-1.17.3-cp310-cp310-win_amd64.whl.metadata (4.6 kB)
  Using cached onnxruntime-1.17.1-cp310-cp310-win_amd64.whl.metadata (4.4 kB)
  Using cached onnxruntime-1.17.0-cp310-cp310-win_amd64.whl.metadata (4.3 kB)
  Using cached onnxruntime-1.16.3-cp310-cp310-win_amd64.whl.metadata (4.5 kB)
  Using cached onnxruntime-1.16.2-cp310-cp310-win_amd64.whl.metadata (4.4 kB)
  Using cached onnxruntime-1.16.1-cp310-cp310-win_amd64.whl.metadata (4.3 kB)
  Using cached onnxruntime-1.16.0-cp310-cp310-win_amd64.whl.metadata (4.2 kB)
  Using cached onnxruntime-1.15.1-cp310-cp310-win_amd64.whl.metadata (4.1 kB)
  Using cached onnxruntime-1.15.0-cp310-cp310-win_amd64.whl.metadata (4.0 kB)
  Using cached onnxruntime-1.14.1-cp310-cp310-win_amd64.whl.metadata (4.0 kB)
Collecting llama-index-readers-file<0.3.0,>=0.2.0 (from llama-index->-r requirements.txt (line 7))
  Using cached llama_index_readers_file-0.2.1-py3-none-any.whl.metadata (5.4 kB)
Collecting llama-index-multi-modal-llms-openai<0.3.0,>=0.2.0 (from llama-index->-r requirements.txt (line 7))
  Downloading llama_index_multi_modal_llms_openai-0.2.2-py3-none-any.whl.metadata (678 bytes)
Collecting llama-index-llms-openai<0.3.0,>=0.2.10 (from llama-index->-r requirements.txt (line 7))
  Downloading llama_index_llms_openai-0.2.15-py3-none-any.whl.metadata (3.3 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\shen\.conda\envs\thinkRAG\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\shen\.conda\envs\thinkRAG\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\shen\.conda\envs\thinkRAG\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\shen\.conda\envs\thinkRAG\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\Users\shen\.conda\envs\thinkRAG\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\shen\.conda\envs\thinkRAG\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\shen\.conda\envs\thinkRAG\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

**Comment by wzdavid** [comment]
谢谢反馈！Windows操作系统有这个问题，后续会优化

**Comment by shenxiaolong57** [comment]
我在wsl环境下部署仍然有此问题

**Comment by davichi11** [comment]
mac也是这问题

**Comment by wzdavid** [comment]
已更新requirements.txt，请重试并反馈
