### ISSUE TITLE
LLAMA_INDEX does not comply with Ollama 0.4

### ISSUE THREAD

**Issue by ray-linn** [wzdavid/ThinkRAG#8]
I noticed ThinkRAG does not comply with Ollama 0.4, for example 
in the server/models/ollama.py - 

st.session_state.ollama_models.append(model["name"]) 

will report an error "object has no field "name", change the "name" to "model" will fix the problem.

the worse, the python module llama_index also has a lot of similar issue related with Ollama 0.4, and they has no plan to fix it yet.

so please limits the ollama version to 0.3 in readme.md.

**Comment by wzdavid** [comment]
Thank you. I will make updates.

**Comment by wzdavid** [comment]
limited to use ollama 0.3.3 in requirements.txt and tested OK
